version: '3.5'

services:
  microservice:
    container_name: microservice_container
    build: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123456}
      POSTGRES_DB: ${POSTGRES_DB:-postgres_db}
      PGDATA: ${PGDATA:-/data/postgres}
    volumes:
      - microservice:${PGDATA:-/data/postgres}
    ports:
      - "${DB_PORT:-5432}:5431"
    networks:
      - microservice
    restart: unless-stopped

  pgadmin_microservice:
    container_name: pgadmin_microservice_container
    build: ./pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-123456}
    volumes:
      - pgadmin_microservice:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5051}:80"
    networks:
      - microservice
    restart: unless-stopped

networks:
  microservice:
    driver: bridge

volumes:
  microservice: 
  pgadmin_microservice: 